-- ==========================================
-- SCRIPT SCHEMA DATABASE SUPABASE (SISIL)
-- Jalankan script ini di SQL Editor Supabase Anda
-- ==========================================

-- 1. TABEL USERS (Profil Tambahan untuk Auth)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    nama TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'mahasiswa' CHECK (role IN ('mahasiswa', 'staff', 'admin')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Aktifkan Row Level Security (RLS) jika diperlukan, atau bypass untuk sementara waktu
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 2. TABEL RUANGAN
CREATE TABLE IF NOT EXISTS public.ruangan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_ruang TEXT UNIQUE NOT NULL,
    kapasitas INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.ruangan ENABLE ROW LEVEL SECURITY;

-- 3. TABEL PERALATAN & BAHAN
CREATE TABLE IF NOT EXISTS public.peralatan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_alat TEXT NOT NULL,
    jenis TEXT NOT NULL DEFAULT 'alat' CHECK (jenis IN ('alat', 'bahan')), -- 'bahan' untuk habis pakai
    kondisi TEXT NOT NULL DEFAULT 'baik',
    jumlah_total INT NOT NULL DEFAULT 0,
    jumlah_tersedia INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.peralatan ENABLE ROW LEVEL SECURITY;

-- 4. TABEL PEMINJAMAN (Utama)
CREATE TABLE IF NOT EXISTS public.peminjaman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    ruang_id BIGINT REFERENCES public.ruangan(id) ON DELETE SET NULL,
    waktu_mulai TIMESTAMPTZ NOT NULL,
    waktu_selesai TIMESTAMPTZ NOT NULL,
    tujuan_peminjaman TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'disetujui', 'ditolak', 'dibatalkan')),
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.peminjaman ENABLE ROW LEVEL SECURITY;

-- 5. TABEL PEMINJAMAN DETAIL ALAT (Banyak-ke-Banyak)
CREATE TABLE IF NOT EXISTS public.peminjaman_detail_alat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peminjaman_id BIGINT NOT NULL REFERENCES public.peminjaman(id) ON DELETE CASCADE,
    alat_id BIGINT NOT NULL REFERENCES public.peralatan(id) ON DELETE CASCADE,
    jumlah_pinjam INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.peminjaman_detail_alat ENABLE ROW LEVEL SECURITY;

-- 6. TABEL LAPORAN KERUSAKAN
CREATE TABLE IF NOT EXISTS public.laporan_kerusakan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    alat_id BIGINT NOT NULL REFERENCES public.peralatan(id) ON DELETE CASCADE,
    deskripsi_kerusakan TEXT NOT NULL,
    status_laporan TEXT NOT NULL DEFAULT 'baru' CHECK (status_laporan IN ('baru', 'diproses', 'selesai')),
    tanggal_lapor TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.laporan_kerusakan ENABLE ROW LEVEL SECURITY;


-- ==========================================================
-- POLICIES (RLS) - IZINKAN AKSES UNTUK MEMPERMUDAH INTEGRASI
-- ==========================================================

-- Policy Tabel Users
CREATE POLICY "Allow public read access to users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow individual insert/update to users" ON public.users FOR ALL USING (auth.uid() = id);

-- Policy Tabel Ruangan
CREATE POLICY "Allow public read access to ruangan" ON public.ruangan FOR SELECT USING (true);
CREATE POLICY "Allow admin all access to ruangan" ON public.ruangan FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Policy Tabel Peralatan
CREATE POLICY "Allow public read access to peralatan" ON public.peralatan FOR SELECT USING (true);
CREATE POLICY "Allow admin all access to peralatan" ON public.peralatan FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Policy Tabel Peminjaman
CREATE POLICY "Allow users to view own or all bookings" ON public.peminjaman FOR SELECT USING (
  auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);
CREATE POLICY "Allow users to insert booking" ON public.peminjaman FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users/admin to update/delete booking" ON public.peminjaman FOR ALL USING (
  auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Policy Tabel Peminjaman Detail Alat
CREATE POLICY "Allow users/admin to access details" ON public.peminjaman_detail_alat FOR ALL USING (true);

-- Policy Tabel Laporan Kerusakan
CREATE POLICY "Allow users to see own/all reports" ON public.laporan_kerusakan FOR SELECT USING (
  auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);
CREATE POLICY "Allow users to insert report" ON public.laporan_kerusakan FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow admin to update/delete report" ON public.laporan_kerusakan FOR ALL USING (
  EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin')
);
